[workspace]
resolver = "2"
members = [
    "types",
    "backend",
    "backend-opencode",
    "tui",
    "native",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-only"

[workspace.dependencies]
ocpncord-types = { path = "types" }
ocpncord-backend = { path = "backend" }
serde = { version = "1", default-features = false, features = ["derive", "alloc"] }
futures-core = { version = "0.3", default-features = false, features = ["alloc"] }
ratatui-core = { version = "0.1", default-features = false }
ratatui = { version = "0.30", default-features = false }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
