[workspace]
resolver = "2"
members = ["backend", "backend-opencode", "tui", "native"]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "AGPL-3.0-only"
readme = "README.md"
repository = "https://github.com/zebreus/ocpncord"
rust-version = "1.91.0"

[workspace.dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
embedded-io-async = "0.7"
embedded-nal-async = "0.9"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-core = { version = "0.3", default-features = false, features = [
    "alloc",
] }
log = { version = "0.4", default-features = false }
ocpncord-backend = { version = "0.3.0", path = "backend" }
ocpncord-backend-opencode = { version = "0.3.0", path = "backend-opencode" }
ocpncord-tui = { version = "0.3.0", path = "tui" }
ratatui = { version = "0.30", default-features = false }
ratatui-core = { version = "0.1", default-features = false }
reqwless = { version = "0.14", default-features = false }
serde = { version = "1", default-features = false, features = [
    "derive",
    "alloc",
] }
serde_json = { version = "1", default-features = false, features = ["alloc"] }
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "time",
    "sync",
    "net",
    "io-util",
] }
