[package]
name = "ocpncord-backend-opencode"
description = "no_std opencode HTTP Backend implementation for ocpncord."
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
keywords = ["ocpncord", "opencode", "http", "embedded", "no-std"]
categories = ["api-bindings", "asynchronous", "embedded", "no-std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
ocpncord-backend.workspace = true
futures-core.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwless.workspace = true
embedded-io-async.workspace = true
embedded-nal-async.workspace = true

[dev-dependencies]
futures.workspace = true
embedded-nal-async.workspace = true
embedded-io-async = { workspace = true, features = ["std"] }
tokio.workspace = true
